# Generated by Django 3.2.3 on 2021-06-13 16:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ongoingjobs',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
