# Generated by Django 3.2.3 on 2021-06-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hops', '0002_ongoingjobs_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ongoingjobs',
            name='name',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
